version: "3.8"

services:
  bookmark-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookmark_data
    networks:
      - bookmark-network
networks:
  bookmark-network: